### ISSUE TITLE
Adding request headers 

### ISSUE THREAD

**Issue by boneysaju** [mailosaur/cypress-mailosaur#11]
Hello,
I am using the mailosaurGetMessage method and would like to pass two request headers through - which will bypass the need for me to log in using my gmail to access our testing environment 
Is there a way I can add this in? 

Thanks

**Comment by andosaur** [comment]
Hi, Do you still have this issue? It sounds like you're behind an authenticated proxy perhaps? Please get in touch with support@mailosaur.com so we can investigate further.
