### ISSUE TITLE
Usage with TypeScript

### ISSUE THREAD

**Issue by Chernitsov** [mailosaur/cypress-mailosaur#12]
How to use it with TypeScript?

My approach doesn´t work, i get an error:

```
Error: Webpack Compilation Error
/Users/user/Projekte/project/app/projects/registrieren/e2e/integration/email.spec.ts
./projects/registrieren/e2e/integration/email.spec.ts
[tsl] ERROR in /Users/user/Projekte/project/app/projects/registrieren/e2e/integration/email.spec.ts(11,6)
      TS2339: Property 'mailosaurGetMessage' does not exist on type 'cy & EventEmitter'.
```

Cypress version: 6.2.1
Cypress-mailsaur version: 2.1.1

Same as here https://github.com/mailosaur/cypress-mailosaur/issues/6

UPDATE:

It seems to work, when the types be declared separately in global module.
```typescript
import 'cypress-mailosaur';
import { Cypress as MailosaurCypress } from 'cypress-mailosaur/src/mailosaurCommands';

declare global {
  namespace Cypress {
    interface Chainable extends MailosaurCypress.Chainable {}
  }
}
```

**Comment by miluoshi** [comment]
@Chernitsov I've fixed this in my PR. After that is merged you don't need to add any global augumentations manually, just importing `import 'cypress-mailosaur'` will suffice.

cc @hippyhorse

**Comment by adjerbetian** [comment]
@Chernitsov Great thanks! :clap: 
Do not hesitate to tell us when you will publish this fix to npm :blush:.

**Comment by miluoshi** [comment]
@adjerbetian I'm not the repo owner, I just fixed the issue I had, so we'll need to wait for the owners to merge it and release it 🙂

**Comment by adjerbetian** [comment]
@miluoshi My bad, I thought this was already merged since the issue was closed.
I'll watch the PR then, thanks!
