### ISSUE TITLE
message html property does not return the complete html with images

### ISSUE THREAD

**Issue by mysticdevx** [mailosaur/cypress-mailosaur#26]
Hi,
I am trying to write the HTML body with images to the cypress browser to be more flexible to make assertions on the email, and even a visual assertion of the email. However, the images are missing. Is there any way to load the complete HTML with images by using only cypress-mailosaur plugin?

**Comment by hippyhorse** [comment]
Hey @mysticdevx - this isn't *currently* possible without some hacking, but if you contact us via support@mailosaur.com we can better understand the use case and may be able to see if this can get on the roadmap.
