### ISSUE TITLE
Buffer is undefined when running webpack 5 and angular.

### ISSUE THREAD

**Issue by srenbo** [mailosaur/cypress-mailosaur#27]
The newest iteration of angular does not include Node.js modules in the build, which means Buffer is not included. 

This leads to a `Buffer is not defined` error when using til lib.

I've fixed it in my build by adding the 'buffer' package and adding

`const Buffer = require('buffer/').Buffer;`

to request.js

**Comment by marcelobrito** [comment]
https://github.com/webpack/changelog-v5/issues/10

**Comment by filiphric** [comment]
thanks @marcelobrito, I read this. however I’m facing the same problem but not with webpack but with vite. adding the mentioned import into `request.js` file solves it there as well, that’s why it made sense to me to update this package. But I’m assuming that I may have a knowledge gap into what is actually happening with the whole buffer thing 🤔

**Comment by hippyhorse** [comment]
@marcelobrito @filiphric Just to confirm - are you using the library in the browser? Buffer should be globally defined in Node, but I'm assuming you're packing code for a browser-based implementation?

**Comment by filiphric** [comment]
@hippyhorse yeah it’s executed in browser, but Cypress tests **are** executed in browser. I’m not sure how would it be possible to execute mailosaur plugin on server side when running in Cypress, can you give me an example of what you have in mind?

**Comment by hippyhorse** [comment]
@filiphric Whilst Cypress tests and most commands are executed in the browser, several of the plugin aspects use a Node.js runtime behind the scenes (which is what I believe allowed Buffer to work in our tests here). Either way, we've just pushed version 2.6.0 which has a polyfill that uses `btoa` if available instead.

Let us know if this works on your side!

**Comment by hippyhorse** [comment]
Closing issue as we believe this is now fixed
