### ISSUE TITLE
Undocumented option errorOnTimeout

### ISSUE THREAD

**Issue by devopsix** [mailosaur/cypress-mailosaur#28]
When a timeout has occured, `options.errorOnTimeout ` is tested in order to determine if the command should error or not in [mailosaurCommands.js, l. 161](https://github.com/mailosaur/cypress-mailosaur/blob/2.4.0/src/mailosaurCommands.js#L161).

This option is not a property of the [`SearchOptions` interface](https://github.com/mailosaur/cypress-mailosaur/blob/32532b9b0c68c3f60be4ed5fd02f6a948a52e671/src/mailosaurCommands.d.ts#L332). But this interface has a `suppressError` property which seems to be unused.

I am wondering if that option is undocumented intentionally or if it should actually have been renamed in commit 76de3466d5626ea963db3386c238b5ecc9150ddf.

**Comment by hippyhorse** [comment]
Hi @devopsix 

The `suppressError` functionality is only in use with the `mailosaurGetMessage` command (which uses the search command itself). This is because we had asks from customers to allow this command to support the concept of expecting a result not to be found for the given criteria.

The search commands themselves though do not require this functionality, as it should never timeout when searching.

**Comment by devopsix** [comment]
Are the [provided types](https://github.com/mailosaur/cypress-mailosaur/blob/master/src/mailosaurCommands.d.ts) possibly not 100% in line with what the code actually does?

![image](https://user-images.githubusercontent.com/58369032/143498304-98cbae46-3e99-40c5-abf0-046d1acfe5f2.png)

![image](https://user-images.githubusercontent.com/58369032/143498262-527f5ecd-e63c-4b11-b0bb-2bdce9c6e41a.png)

![image](https://user-images.githubusercontent.com/58369032/143500549-5d5c4a9b-db1d-4381-8e87-25c39c712a30.png)

Calling the `errorOnTimeout` option “undocumented” may be slighty misleading as it actually is mentioned in [How to test email and SMS with Cypress](https://mailosaur.com/docs/frameworks-and-tools/cypress/#options-2). But due to the types provided for cypress-mailosaur, in Typescript projects, IDE content assist features suggest something which is not actually working:

```typescript
const serverId = Cypress.env('MAILOSAUR_SERVER_ID');

describe('mailosaurSearchMessages', async () => {
  it('fails', () => {
    cy.mailosaurSearchMessages(
      serverId,
      {sentTo: `nothing-ever-sent-to@${serverId}.mailosaur.com`},
      // IDE suggests suppressError.
      // But it will fail with “No matching messages found in time.” because suppressError is not tested in the command.
      {timeout: 500, suppressError: true}
    )
      .its('items')
      .should('have.length', 0);
  });

  it('succeeds', () => {
    cy.mailosaurSearchMessages(
      serverId,
      {sentTo: `nothing-ever-sent-to@${serverId}.mailosaur.com`},
      // Will succeed because errorOnTimeout is what is actually tested in mailosaurSearchMessages.
      // Have to use “@ts-ignore” here because errorOnTimeout is not a property of SearchOptions.
      // @ts-ignore
      {timeout: 500, errorOnTimeout: false}
    )
      .its('items')
      .should('have.length', 0);
  });
});

describe('mailosaurGetMessage', async () => {
  it('fails', () => {
    cy.mailosaurGetMessage(
      serverId,
      {sentTo: `nothing-ever-sent-to@${serverId}.mailosaur.com`},
      // @ts-ignore
      // If SearchOptions.suppressError was simply renamed to errorOnTimeout this would seem valid:
      {timeout: 500, errorOnTimeout: false}
      // But it will fail with “Cannot read properties of undefined (reading 'id')”.
      // The options arguments of mailosaurSearchMessages and mailosaurGetMessage should be typed differently
      // so that neither suppressError nor errorOnTimeout is suggested.
    )
      .its('items')
      .should('have.length', 0);
  });
});
```

![image](https://user-images.githubusercontent.com/58369032/143501428-6a1d965d-0f17-497f-bbc0-288db6f782e1.png)

**Comment by hippyhorse** [comment]
Good catch @devopsix, the `supressError` reference is a hang-over from a previous version, this is now fixed in version 2.5.2 of the client. The comments over this property also further clarifies that this is intended for use with `mailosaurGetMessage` too.

**Comment by devopsix** [comment]
@hippyhorse That's great, thank you very much!

When will 2.5.2 be available through npm? Currently, the [most recent version found at npmjs.com seems to be 2.5.1](https://www.npmjs.com/package/cypress-mailosaur).

Is it possible something has gone wrong with the [2.5.2 release build job](https://github.com/mailosaur/cypress-mailosaur/actions/runs/1525437209)?

**Comment by hippyhorse** [comment]
You're absolutely right, version 2.5.6 should now be live!
