### ISSUE TITLE
cy.wrap() timed out waiting 4000ms to complete.

### ISSUE THREAD

**Issue by johnmpotter** [mailosaur/cypress-mailosaur#3]
Hey there, 

I'm running into a CypressError when calling cy.mailosaurGetMessage: `cy.wrap() timed out waiting 4000ms to complete.`

This is likely because the email is taking too long to send so I need to wait a little longer. I just started using both Cypress and Mailosaur so I could be missing something, but it seems like it's due to Cypress' default timeout. If that's the case, could you accept an option that sets the timeout for `cy.wrap()`? I can work around it by increasing the `defaultCommandTimeout` in the Cypress config, but would prefer not to have it increased for all commands.

Thanks for the help!
John

**Comment by todd-m-kemp** [comment]
I am also experiencing this problem.

The error is coming from `mailosaurCommands.js` line 141.

![image](https://user-images.githubusercontent.com/62152998/88090857-2ff16380-cb5c-11ea-9e51-73f4fa9f2975.png)

The problem occurs only sporadically but regrettably it is making the tests very flaky.

**Comment by hippyhorse** [comment]
Sorry for the crazy delay in picking this one up, we are looking to take this on in our next sprint. We'll update asap.

**Comment by hippyhorse** [comment]
Just to confirm, having looked into this, we fixed this earlier in the year following another support case. The timeout is now automatically set; this will be 10s by default when using `cy.mailosaurGetMessage`

**Comment by todd-m-kemp** [comment]
Thanks so much for the information. I'll go ahead and upgrade right away! 😄
