### ISSUE TITLE
Can't get an email message when two searchParameters added

### ISSUE THREAD

**Issue by bjuzefczyk** [mailosaur/cypress-mailosaur#48]
Hello,
when I use sentTo and subject parameters at the same time:

```
cy.mailosaurGetMessage(serverId, {
    sentTo: emailAddress,
    subject: 'Aktivierung Ihres Zugangs',
}, { timeout: 30000 } 
).then((email) => {
    const confirmationCode = /invitationCode=(\d{6})/.exec(email.html.body)[1];
});
```

then I get really often this error:

![Screenshot 2022-11-10 at 11 32 48](https://user-images.githubusercontent.com/48711384/201068144-0545a847-0623-41c3-acd4-dd826279c47d.png)

And what is strange when I change to:
```
cy.mailosaurGetMessage(serverId, {
    sentTo: emailAddress,
}, { timeout: 30000 } 
).then((email) => {
    const confirmationCode = /invitationCode=(\d{6})/.exec(email.html.body)[1];
    expect(email.subject).to.equal('Aktivierung Ihres Zugangs');
});
```
~~I don't get the error~~ The exception appears but only from time to time.

Do you have any idea why it doesn't work or what I do wrong?

Edit:
Timeline
13:42:18 - click register button (send confirmation code via email)
[execute cy.mailosourGetMessage]
13:42:21 - email appears in mailosaur mailbox
13:42:48 exception thrown (screenshot above)

**Comment by hippyhorse** [comment]
Closing as not related to the client itself, discussion continuing in support channel.
