### ISSUE TITLE
Is it possible to check the validation code sent to the email via API or does it only work via UI?

### ISSUE THREAD

**Issue by guilhermesousa-cwi** [mailosaur/cypress-mailosaur#54]
I am running tests via API and it returns the following message: "No matching messages found in time. By default, only messages received in the last hour are checked (use receivedAfter to override this)." However, when testing via UI, everything is okay.

![image](https://user-images.githubusercontent.com/118919569/224523309-07e821c8-70da-4c2f-9c92-9d43b7f35b4d.png)

"cypress": "^11.2.0"
"cypress-mailosaur": "^2.13.0"

**Comment by hippyhorse** [comment]
This will usually mean there is an issue with how you're calling the code - please contact our support team via the website who can help you out here.

**Comment by guilhermesousa-cwi** [comment]
This problem has reoccurred 8 months after that issue. I've noticed that the email sent has a significant delay in landing in the MailoSaur inbox.

I've already sent an email to support; now, all we need is to have faith.
