### ISSUE TITLE
Feature Request: Optional Configuration Variable for Handling "No Matching Messages Found in Time" Error in Cypress Mailosaur

### ISSUE THREAD

**Issue by CaiqueCoelho** [mailosaur/cypress-mailosaur#66]
**Subject:** Introducing a Non-Error Handling Option for Email Fetch Timeout in Cypress Mailosaur

## Description:

Hello Mailosaur Team,

I am writing to propose a feature addition to the Cypress Mailosaur plugin. Currently, when the plugin attempts to fetch an email or SMS and doesn't find a matching message within the specified time frame, it throws an error: "No matching messages found in time." This behavior is generally helpful for ensuring tests are accurately awaiting email/sms receipt. However, in some testing scenarios, it would be beneficial to have the option to treat this situation non-critically, without throwing an error.

## Proposed Feature:

I suggest introducing an optional configuration variable (e.g., allowNoMessages) that, when set, alters the behavior of the email/sms fetching process. Specifically, instead of throwing an error when no matching messages are found within the timeout period, the plugin would return a null or specific response indicating the absence of emails. This behavior would be optional and controlled by the new configuration variable, preserving the current default behavior for users who do not opt-in to this feature.

## Use Case:

This feature would be particularly useful in test scenarios where the absence of an email/sms is a valid condition and should not result in a test failure. For example, testing the non-receipt of an email/sms based on certain application behaviors or user actions.

## Benefits:

Flexibility in Test Scenarios: Allows for more nuanced testing conditions, especially in cases where the non-receipt of an email is part of the test requirements.
Reduced False Positives: Helps in avoiding false positives in test results due to the strict handling of the email fetch timeout.
Customizable Test Flows: Offers users the ability to tailor their test flows more precisely according to their specific needs.
I believe this enhancement would significantly benefit the Cypress Mailosaur user community by providing greater control and flexibility in handling email fetch scenarios.

Thank you for considering this request. I am looking forward to any feedback or discussion regarding this proposed feature.

Best regards,

Caíque Coelho

**Comment by jm-mailosaur** [comment]
Hi @CaiqueCoelho

Thanks for this feature request, however you should be able to already do this using the `cy.mailosaurSearchMessages` command and `errorOnTimeout` option.

Using code like the below, you should be able to achieve what you're looking for:

```js
cy.mailosaurSearchMessages(server, {
  sentTo: '{email address here}',
}, {
  errorOnTimeout: false, // when set to false, no error will be thrown if there are no results
}).then((result) => {
  expect(result.items).to.be.an('array').that.has.lengthOf(0);
});
```

**Comment by CaiqueCoelho** [comment]
Awesome, thank you so much!
