### ISSUE TITLE
Server occasionally responds with Invalid Server identifier

### ISSUE THREAD

**Issue by abhirathore2006** [mailosaur/cypress-mailosaur#9]
I have noticed that server occasionally sends  below error even when request options are valid and email actually exists
```json
{
    "type": "ValidationError",
    "messages": {
        "server": "Invalid Server identifier."
    }
}
```

i have done investigation using post request via postman and it seems issue with the proxy/load balancer, every once in a while request seems to be landing on server on which data is not synced yet and it responds with above error

Steps To reproduce

1.  Create Postman request with "sentTo" criteria
2.  hit request 4-10 times you will get failure in few of them

# Setup Info
```
 "cypress": "4.12.1",
 "cypress-mailosaur": "1.0.6"
```

I have also noticed one more issue and cause might be the same, client is able to fetch message list from above criteria but message details request fails with 404

**Comment by hippyhorse** [comment]
Hey there, if you're still encountering this issue we would need more information about your account. If this is not working, please contact us at support@mailosaur.com
